### PR TITLE
Not to create unnessary tensorflow variables when sampling

### PR DESCRIPTION
**Pull request by MingStar**
The tensorflow variable `self.lr` is really for traning only, as well as the variable self.train_op.

### CODE REVIEW

**Comment by hunkim** [comment]
I think these changes are interesting, but IMHO, there are too many features in one PR. 

I guess it would be better if you can split them and submit separate PRs for each feature such as temperature, saving best results, web server, dropouts, etc.? I am also not sure having a web-server implementation in char-rnn is a good idea.

For the dropouts, is this similar to #35?

**Comment by MingStar** [comment]
Sorry. was meant to request for one commit only.

I will create a separate branch and edit the pull request.

**Comment by MingStar** [comment]
Will create a new pull request for this.

**Comment by hunkim** [comment]
Thanks!

**Pull request closed without merging**
