### PR TITLE
Simple tests on Travis CI - part 2

### PR DESCRIPTION
**Pull request by hugovk**
Builds on #74 by running some basic commands to check they can at least run on each Python version without exceptions. Also runs them with coverage.

```yml
 - coverage run --append --include=./* train.py --data_dir data/teenytinyshakespeare
 - coverage run --append --include=./* train.py --data_dir data/teenytinyshakespeare --init_from save
 - coverage run --append --include=./* sample.py
```

Also sends coverage to Coveralls; enable this repo [here](https://coveralls.io/repos/new).

### CODE REVIEW

**Comment by hugovk** [comment]
@sherjilozair Is this okay to be merged?

**Comment by ubergarm** [comment]
@hugovk I just checked out your CI over at https://travis-ci.org/hugovk/char-rnn-tensorflow 

Looks like you got it working pretty well, might be some `flake8` stuff to fixup. 

I like the style guide of:
1.  `flake8 --max-line-length=120`
2. ```foo = long_function_name(var_one,
                         var_two,
                         var_three)
```

**Comment by ubergarm** [comment]
I'll try this out on my fork and patch in your extensive `.gitignore` soon.

**Comment by ubergarm** [comment]
@sherjilozair when you have a chance, can you:

1. sign onto https://travis-ci.org/profile 
2. add the repo https://github.com/sherjilozair/char-rnn-tensorflow/ 

I couldn't find a way to add it myself, maybe some permissions thing. Easier if you just add it probably.

**Comment by sherjilozair** [comment]
Done! Let me know if you need anything else.

**Comment by ubergarm** [comment]
The tests did hit one odd snag on python 3.4, a segfault?!  There is a chance that if `sample.py` generates an odd character perhaps the coverage test fails?

https://travis-ci.org/ubergarm/char-rnn-tensorflow/jobs/210137899#L272-L281

I'll go ahead and merge this and we can keep an eye on on how the builds work before putting up a shield. :)

**Comment by ubergarm** [comment]
@hugovk Thanks for this sweet travis ci and coverage capability!  I just added the coverage badge as it looks good, but don't want to add the build status badge until the heisenbug gets figured out:  https://travis-ci.org/sherjilozair/char-rnn-tensorflow

Any thoughts why the builds don't seem to be deterministic on pass/fail?  That `segfault` business seems fishy.

**Comment by ubergarm** [comment]
Now that we have a few data points, seems most likely to fail on Python 3.5 and 3.4 anecdotally... I'm only testing w/ 2.7 locally still, I'd like to get on 3.6... 

If it really is failing on 3.5, that'd be bad as it is pretty widespread. Hrmm.

**Pull request merged**
