### PR TITLE
Adding a bidirectional neural network

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
ref #63

### CODE REVIEW

**Comment by hugovk** [comment]
@martiansideofthemoon This PR has merge conflicts.

**Comment by wichtounet** [comment]
Have you had good results with this PR ? I've adapted on some code derived from this project and it didn't predict anything useful. 

(Would also be great if the PR could contain only the Bidirectional part)

**Comment by martiansideofthemoon** [comment]
No, I did not get very good results @wichtounet. It is also messing up the perplexity calculations. It makes little sense for a "next" character predictor I feel

**Comment by wichtounet** [comment]
@martiansideofthemoon Thanks for the answer. I had quite good perplexity during training, but the next character prediction was not good at all.

**Comment by martiansideofthemoon** [comment]
@wichtounet, if you are using the perplexity metric in the PR, it's not correct since the RNN has *seen* the future while predicting the next character.

**Comment by martiansideofthemoon** [comment]
Closing this for now @wichtounet, it's kind of pointless for a language model

**Pull request closed without merging**
