### PR TITLE
when training, model can be initialized from previously saved model

### PR DESCRIPTION
**Pull request by wohnjayne**
implements the --init-from as in char-rnn.

note that this implements model initialization only - optimization specific params (such as the previous learning rate/epoch/batch number) are not restored

### CODE REVIEW

**Comment by sherjilozair** [comment]
@wohnjayne Cool! This is really useful. I'll make sure I play with this later today. Thanks for your contribution.

**Comment by hunkim** [comment]
This is cool. Is it merged?

**Comment by bver** [comment]
+1 for this proposal.

**Comment by hunkim** [comment]
+1

**Comment by sherjilozair** [comment]
I can merge this if the merge conflicts are fixed.

**Comment by wohnjayne** [comment]
Sorry, I wasn't aware of the upstream changes. Should be ready to merge now

**Comment by sherjilozair** [comment]
Thanks!

**Pull request merged**
